# Generated by Django 5.2.12 on 2026-03-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('cameras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='agents.agent'),
        ),
    ]
