# Generated by Django 5.2.12 on 2026-03-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('camera.online', 'Câmera Online'), ('camera.offline', 'Câmera Offline'), ('motion.detected', 'Movimento Detectado'), ('alpr.detected', 'Placa Detectada'), ('intrusion.detected', 'Intrusão Detectada'), ('fire.detected', 'Incêndio Detectado'), ('video.loss', 'Perda de Vídeo'), ('tampering.detected', 'Tamper Detectado'), ('line_crossing.detected', 'Cruzamento de Linha'), ('face.detected', 'Face Detectada')], max_length=50),
        ),
    ]
