# Generated by Django 4.2.11 on 2026-03-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0002_roi_config_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionofinterest',
            name='ia_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
