# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('camera.online', 'Câmera Online'), ('camera.offline', 'Câmera Offline'), ('motion.detected', 'Movimento Detectado'), ('alpr.detected', 'Placa Detectada'), ('intrusion.detected', 'Intrusão Detectada'), ('fire.detected', 'Incêndio Detectado')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
