# Generated by Django 5.2.12 on 2026-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_initial'),
        ('events', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_tenant__97b6e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_camera__a025de_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='confidence',
            field=models.FloatField(blank=True, db_index=True, help_text='Nível de confiança da detecção (para eventos ALPR)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='plate',
            field=models.CharField(blank=True, db_index=True, help_text='Placa do veículo (para eventos ALPR)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Dados específicos do evento em formato JSON'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_even_created_52c227_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', '-created_at'], name='events_even_tenant__950ad9_idx'),
        ),
        migrations.AlterModelTable(
            name='event',
            table='events_event',
        ),
    ]
