# Generated by Django 5.2.12 on 2026-03-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rtsp_url', models.URLField(blank=True)),
                ('manufacturer', models.CharField(choices=[('hikvision', 'Hikvision'), ('intelbras', 'Intelbras'), ('dahua', 'Dahua'), ('other', 'Outro')], default='other', max_length=20)),
                ('retention_days', models.IntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias')], default=7)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
