# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['tenant', 'is_online'], name='cameras_cam_tenant__ffbcd4_idx'),
        ),
    ]
