# Generated by Django 5.2.12 on 2026-03-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('alpr', 'ALPR'), ('mediamtx', 'MediaMTX'), ('onvif', 'ONVIF'), ('other', 'Outro')], max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(default=200)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='webhooks_we_source_1a2761_idx')],
            },
        ),
    ]
