# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['camera', '-started_at'], name='recordings__camera__35d70f_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['tenant', 'status'], name='recordings__tenant__8c1e78_idx'),
        ),
    ]
