# Generated by Django 5.2.12 on 2026-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_initial'),
        ('recordings', '0003_clip_recordingsegment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recordingsegment',
            name='recordings__camera__01fe7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordingsegment',
            name='recordings__tenant__40f569_idx',
        ),
        migrations.AlterField(
            model_name='recordingsegment',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='recordingsegment',
            index=models.Index(fields=['camera', 'start_time'], name='recordings__camera__8636d5_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsegment',
            index=models.Index(fields=['camera', 'end_time'], name='recordings__camera__3d8514_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsegment',
            index=models.Index(fields=['tenant', 'start_time'], name='recordings__tenant__34eae3_idx'),
        ),
    ]
