# Generated by Django 4.2.11 on 2026-03-08 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.JSONField()),
                ('ia_type', models.CharField(choices=[('lpr', 'Reconhecimento de Placas'), ('intrusion', 'Detecção de Intrusão'), ('crowd', 'Detecção de Aglomeração')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='cameras.camera')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='tenants.tenant')),
            ],
            options={
                'db_table': 'regions_of_interest',
                'indexes': [models.Index(fields=['tenant', 'camera'], name='regions_of__tenant__a11e57_idx'), models.Index(fields=['camera', 'active'], name='regions_of__camera__7e4b48_idx')],
            },
        ),
    ]
