# Generated by Django 4.2.11 on 2026-03-08 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roi', '0001_initial'),
        ('cameras', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('lpr', 'Reconhecimento de Placa'), ('intrusion', 'Intrusão'), ('crowd', 'Aglomeração')], max_length=20)),
                ('snapshot_path', models.CharField(max_length=500)),
                ('event_data', models.JSONField()),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='cameras.camera')),
                ('roi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_events', to='roi.regionofinterest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_events',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['tenant', 'detected_at'], name='ai_events_tenant__7ffbf9_idx'), models.Index(fields=['camera', 'event_type'], name='ai_events_camera__3a030d_idx'), models.Index(fields=['detected_at'], name='ai_events_detecte_40fb13_idx')],
            },
        ),
    ]
