# Generated by Django 4.2.11 on 2026-03-08 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('primary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('secondary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('dark_mode_default', models.BooleanField(default=False)),
                ('terms_url', models.URLField(blank=True, null=True)),
                ('privacy_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resellers',
                'indexes': [models.Index(fields=['slug'], name='resellers_slug_dce542_idx'), models.Index(fields=['custom_domain'], name='resellers_custom__276615_idx')],
            },
        ),
    ]
