# Generated by Django 5.2.12 on 2026-03-16 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0003_camera_agent'),
        ('recordings', '0004_remove_recordingsegment_recordings__camera__01fe7e_idx_and_more'),
        ('users', '0002_custom_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ia_type', models.CharField(choices=[('vehicle_dwell', 'Permanência Veicular'), ('intrusion', 'Intrusão'), ('object_detected', 'Detecção de Objetos'), ('crowd', 'Multidão'), ('vehicle_traffic', 'Tráfego Veicular'), ('human_traffic', 'Tráfego Humano'), ('line_crossing', 'Cruzamento de Linha'), ('loitering', 'Perambulação'), ('abandoned_object', 'Objeto Abandonado'), ('queue', 'Fila'), ('heatmap', 'Mapa de Calor'), ('lpr', 'Reconhecimento de Placa'), ('facial', 'Reconhecimento Facial')], default='intrusion', max_length=30)),
                ('polygon_points', models.JSONField(default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='cameras.camera')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DwellEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('dwell_seconds', models.IntegerField(blank=True, null=True)),
                ('frame_path', models.CharField(blank=True, max_length=512)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwell_events', to='cameras.camera')),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dwell_events', to='recordings.clip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwell_events', to='users.tenant')),
                ('roi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dwell_events', to='analytics.regionofinterest')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='regionofinterest',
            index=models.Index(fields=['camera', 'is_active'], name='analytics_r_camera__358cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='regionofinterest',
            index=models.Index(fields=['tenant', 'ia_type'], name='analytics_r_tenant__e0af3d_idx'),
        ),
        migrations.AddIndex(
            model_name='dwellevent',
            index=models.Index(fields=['camera', '-entered_at'], name='analytics_d_camera__de5ded_idx'),
        ),
        migrations.AddIndex(
            model_name='dwellevent',
            index=models.Index(fields=['tenant', 'is_valid'], name='analytics_d_tenant__6ceb35_idx'),
        ),
        migrations.AddIndex(
            model_name='dwellevent',
            index=models.Index(fields=['tenant', '-entered_at'], name='analytics_d_tenant__857087_idx'),
        ),
    ]
