# Generated by Django 5.2.12 on 2026-03-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_face_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facedetectionevent',
            new_name='analytics_f_tenant__2bd209_idx',
            old_name='analytics_f_tenant_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='facedetectionevent',
            new_name='analytics_f_camera__221df3_idx',
            old_name='analytics_f_camera_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='facedetectionevent',
            new_name='analytics_f_tenant__7a0401_idx',
            old_name='analytics_f_tenant_unk_idx',
        ),
        migrations.RenameIndex(
            model_name='faceprofile',
            new_name='analytics_f_tenant__0d80b0_idx',
            old_name='analytics_f_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='faceprofile',
            new_name='analytics_f_tenant__7bad76_idx',
            old_name='analytics_f_tenant_cpf_idx',
        ),
        migrations.AlterField(
            model_name='facedetectionevent',
            name='is_unknown',
            field=models.BooleanField(default=False, help_text='True = rosto não identificado na base de cadastros.'),
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF para direito de exclusão LGPD (formato: 000.000.000-00).', max_length=14),
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='embedding',
            field=models.JSONField(help_text='Vetor de embedding facial 512-dim (ArcFace).'),
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='lgpd_consent',
            field=models.BooleanField(default=False, help_text='Consentimento explícito do titular para uso biométrico.'),
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='name',
            field=models.CharField(help_text='Nome completo da pessoa.', max_length=255),
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações (cargo, acesso, etc.).'),
        ),
    ]
