# Generated by Django 5.2.12 on 2026-03-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'event_type'], name='events_even_tenant__97b6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['camera', '-created_at'], name='events_even_camera__a025de_idx'),
        ),
    ]
