FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY analytic_workers/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY analytic_workers/ ./analytic_workers/
COPY common/ ./common/

ENV PYTHONUNBUFFERED=1
