# Generated by Django 5.2.12 on 2026-03-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_custom_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo da regra.', max_length=255)),
                ('event_type_pattern', models.CharField(help_text="Padrão do evento (ex: 'detection.alpr', 'camera.*').", max_length=255)),
                ('channel', models.CharField(choices=[('webhook', 'Webhook')], default='webhook', help_text='Canal de entrega.', max_length=50)),
                ('destination', models.CharField(help_text='URL do webhook ou endereço de destino.', max_length=1000)),
                ('is_active', models.BooleanField(default=True, help_text='Se a regra está ativa para novos eventos.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant dono desta regra.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Regra de Notificação',
                'verbose_name_plural': 'Regras de Notificação',
                'db_table': 'notifications_rule',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(blank=True, help_text='ID do evento original se houver relacionamento no BD.', null=True)),
                ('event_type', models.CharField(help_text="Tipo de evento real que disparou (ex: 'detection.alpr').", max_length=255)),
                ('status', models.CharField(help_text="'success' ou 'failed'.", max_length=50)),
                ('response_code', models.IntegerField(blank=True, help_text='Código HTTP retornado pelo webhook.', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Corpo da resposta do destinatário.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationrule')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificação',
                'db_table': 'notifications_log',
            },
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['tenant', 'is_active'], name='notificatio_tenant__bcec21_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['rule', '-created_at'], name='notificatio_rule_id_d3b614_idx'),
        ),
    ]
