# Generated by Django 5.2.12 on 2026-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Chave secreta para assinar webhooks com HMAC-SHA256.', max_length=255),
        ),
    ]
