# Generated by Django 4.2.11 on 2026-03-08 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stream_protocol', models.CharField(choices=[('rtsp', 'RTSP'), ('rtmp', 'RTMP')], max_length=10)),
                ('stream_url', models.CharField(blank=True, max_length=500, null=True)),
                ('stream_key', models.UUIDField(blank=True, editable=False, null=True)),
                ('retention_days', models.IntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias')], default=7)),
                ('ia_enabled', models.BooleanField(default=False)),
                ('ia_status', models.CharField(choices=[('disabled', 'Desabilitado'), ('ia_pending', 'Aguardando Configuração'), ('active', 'Ativo')], default='disabled', max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='tenants.tenant')),
            ],
            options={
                'db_table': 'cameras',
                'indexes': [models.Index(fields=['tenant', 'online'], name='cameras_tenant__31af3f_idx'), models.Index(fields=['tenant', 'ia_enabled'], name='cameras_tenant__2181f7_idx')],
            },
        ),
    ]
