# Generated by Django 4.2.11 on 2026-03-08 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_cameras', models.IntegerField(default=10)),
                ('valid_until', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='resellers.reseller')),
            ],
            options={
                'db_table': 'licenses',
                'indexes': [models.Index(fields=['reseller', 'active'], name='licenses_reselle_df8fda_idx')],
            },
        ),
    ]
