# Generated by Django 5.2.12 on 2026-03-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_initial'),
        ('events', '0003_alter_event_options_and_more'),
        ('recordings', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='recordings__event_i_b6c735_idx'), models.Index(fields=['camera', 'start_time', 'end_time'], name='recordings__camera__515507_idx'), models.Index(fields=['tenant', 'status'], name='recordings__tenant__e69f87_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cameras.camera')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['camera', 'start_time', 'end_time'], name='recordings__camera__01fe7e_idx'), models.Index(fields=['tenant'], name='recordings__tenant__40f569_idx')],
            },
        ),
    ]
