# Generated by Django 4.2.11 on 2026-03-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knownperson',
            new_name='known_perso_tenant__b5b705_idx',
            old_name='known_perso_tenant__active_idx',
        ),
    ]
