# Generated by Django 4.2.11 on 2026-03-08 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0001_initial'),
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=63, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='franchise.license')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='resellers.reseller')),
            ],
            options={
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['subdomain'], name='tenants_subdoma_69cf01_idx'), models.Index(fields=['reseller', 'active'], name='tenants_reselle_dfda50_idx')],
            },
        ),
    ]
